import {
  CLASSIC_CTA_DEFAULTS,
  CLASSIC_CTA_DIMENSIONS,
  CLASSIC_CTA_POSITION,
} from './ClassicCTA';
import {
  SWIPE_UP_CTA_DEFAULTS,
  SWIPE_UP_CTA_DIMENSIONS,
  SWIPE_UP_CTA_POSITION,
} from './SwipeUpCTA';
import {
  IMAGE_CTA_DEFAULTS,
  IMAGE_CTA_DIMENSIONS,
  IMAGE_CTA_POSITION,
} from './ImageCTA';
import {
  VISIT_CTA_DEFAULTS,
  VISIT_CTA_DIMENSIONS,
  VISIT_CTA_POSITION,
} from './VisitCTA';
import {
  DESCRIBE_CTA_DEFAULTS,
  DESCRIBE_CTA_DIMENSIONS,
  DESCRIBE_CTA_POSITION,
  PRODUCT_CARD_CTA_DEFAULTS,
  PRODUCT_CARD_CTA_DIMENSIONS,
  PRODUCT_CARD_CTA_POSITION,
} from './DescribeCTA';
import {
  BUY_CTA_DEFAULTS,
  BUY_CTA_DIMENSIONS,
  BUY_CTA_POSITION,
} from './BuyCTA';

export const CTA_DIMENSIONS = {
  classic: CLASSIC_CTA_DIMENSIONS,
  swipe_up: SWIPE_UP_CTA_DIMENSIONS,
  image: IMAGE_CTA_DIMENSIONS,
  product_card: PRODUCT_CARD_CTA_DIMENSIONS,
  visit_product: VISIT_CTA_DIMENSIONS,
  describe_product: DESCRIBE_CTA_DIMENSIONS,
  buy_product: BUY_CTA_DIMENSIONS,
};

export const CTA_POSITIONS = {
  classic: CLASSIC_CTA_POSITION,
  swipe_up: SWIPE_UP_CTA_POSITION,
  image: IMAGE_CTA_POSITION,
  product_card: PRODUCT_CARD_CTA_POSITION,
  visit_product: VISIT_CTA_POSITION,
  describe_product: DESCRIBE_CTA_POSITION,
  buy_product: BUY_CTA_POSITION,
};

export const CTA_DEFAULTS = {
  classic: CLASSIC_CTA_DEFAULTS,
  swipe_up: SWIPE_UP_CTA_DEFAULTS,
  image: IMAGE_CTA_DEFAULTS,
  product_card: PRODUCT_CARD_CTA_DEFAULTS,
  visit_product: VISIT_CTA_DEFAULTS,
  describe_product: DESCRIBE_CTA_DEFAULTS,
  buy_product: BUY_CTA_DEFAULTS,
};
